# -*- coding: utf-8 -*-
"""Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gELxU6G2IH5xPFSe7FkbwtS-SnD1iTSL

# To understand the influence of the parents background, test preparation etc on students performance
"""



# Importing Necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# reading csv file using pandas

df=pd.read_csv("C:/Users/Hp/Desktop/Practicles/ML/pract2/exams.csv")

rows,columns=df.shape
print("Number of Records are:",rows)
print("Number of features are:",columns)

#Getting the first five lines of the dataframe
df.head()

df.info()
#docstring with literal block and unordered list
print(
"""
Getting the summary of the dataframe::

    -names of the columns
    -non null values count
    -data type of each column

""")

#ordered list
"""
Mathematical summary of the dataframe values ::
    1.count
    2.mean
    3.std
    4.mean
    5.25% values
    6.50% values
    7.75% values
    8.max
"""
df.describe()

df.isna().sum() #Checking for null values which is 0

a=df["gender"].value_counts()
b=df["race/ethnicity"].value_counts()
c=df["parental level of education"].value_counts()
d=df["lunch"].value_counts()
e=df["test preparation course"].value_counts()
print("=================================================")
print("Value counts of Gender:")
print(a)
print("=================================================")
print("Value counts of race:")
print(b)
print("=================================================")
print("Value counts of parent education:")
print(c)
print("=================================================")
print("Value counts of Lunch:")
print(d)
print("=================================================")
print("Value counts of Test preparation course:")
print(e)
print("=================================================")

sns.countplot(df.gender)

sns.countplot(df["race/ethnicity"])

sns.countplot(df["parental level of education"])
plt.subplots_adjust(hspace = 0.8)

sns.countplot(df.lunch)

sns.countplot(df["test preparation course"])

sns.heatmap(df.corr(),annot=True)
plt.subplots_adjust(hspace = 0.8)

df['gender'].replace(['male','female'],[0, 1],inplace=True)
df['race/ethnicity'].replace(['group A', 'group B','group C', 'group D', 'group E'], [0, 1,2,3,4] , inplace=True)
df['parental level of education'].replace(["some college","high school","some high school","associate's degree","bachelor's degree" ,"master's degree"], [0, 1,2,3,4,5], inplace=True)
df['lunch'].replace(["standard","free/reduced"], [0, 1], inplace=True)
df['test preparation course'].replace(['none', 'completed'], [0, 1], inplace=True)

X = df.drop(columns=["math score","reading score","writing score"])
X.head()

fig, ax = plt.subplots()
sns.catplot(x="gender", y="math score", data=df,ax=ax)
sns.catplot(x="race/ethnicity", y="math score", data=df,ax=ax)
sns.catplot(x="parental level of education", y="math score", data=df,ax=ax)
sns.catplot(x="lunch", y="math score", data=df,ax=ax)
sns.catplot(x="test preparation course", y="math score", data=df,ax=ax)

g = sns.PairGrid(X)
g.map(sns.pointplot)

z = (df["math score"]+df["reading score"]+df["writing score"])//3

y = df["math score"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=42)

df.corr()



fig = plt.figure(figsize=(15,15))
ax = fig.add_subplot(111, projection = '3d')

x = df['math score']
y = df['reading score']
z = df['writing score']

ax.set_xlabel("math score of the students")
ax.set_ylabel("reading score of the students")
ax.set_zlabel("writing score of the students")

ax.scatter(x, y, z)

plt.show()



df.hist()
plt.subplots_adjust(hspace = 0.8,wspace=2)

sns.distplot(df["reading score"])
sns.distplot(df["writing score"])
sns.distplot(df["math score"])

sns.boxplot(df["gender"],df['math score'])

sns.boxplot(df["race/ethnicity"],df['math score'])

sns.boxplot(df["parental level of education"],df['math score'])

"""**Conclusion:**
<br> 1.For lunch and test preperation there is lots of difference between the count of each value
<br> 2.There is very good correlation between writing and math score       
<br> 3.In rance/ethenticity order of better avg and min ,max is
<br>      group E>D>C>B>A
<br> 4.Male having little bit higher avg and min max than Female
<br> 5.
<br>
<br>
"""

